### ISSUE TITLE
book property in objects

### ISSUE THREAD

**Issue by daddykom** [DirtyHairy/node-libxl#10] opened 2016-08-04 15:08 UTC
Hello

"Accessing the parent book: sheet, format and font objects hold a reference to their parent book that can be accessed via the book property"

How can i copy a format from one book to the other, like in the libxt-sample "Copying cells with formats to other workbook"? If i made an dstBook.addFormat with the format of the srcBook, the i get a error "parent books differ"

Greetings
Charley

**Comment by DirtyHairy** [comment] 2016-08-04 18:30
Hi Charley!

What you are seeing is not a bug regarding the 'book' reference, but a result of purposeful validation :smirk: In libxl, "book" objects act as factories for the other classes and, as it is unclear to me whether mixing book scopes is a valid operation, I validate that objects share the same "parent" in all operations that involve two different objects.

However, your usecase is perfectly valid, and if this is covered by the official docs, I see no harm in relaxing the restriction in this case. Can you give me a link to the official example?

Cheers
    -Christian

**Comment by DirtyHairy** [comment] 2016-08-05 21:12
Hi Charley!

Thanks for the compliment :smiley: Check out 0.2.19, it should solve your issue.

Cheers
    -Christian

**Comment by DirtyHairy** [comment] 2016-08-26 19:00
Hi Charley!

Any news here? Otherwise I assume that the issue is fixed and will close the issue.

Cheers
    -Christian

**Closed** 2016-10-07 07:59 UTC
